### ISSUE TITLE
Include bidi marks?

### ISSUE THREAD

**Issue by adrianheine** [marijnh/extending-char#1]
Shouldn't the bidi marks be considered extending chars, too? That would apply to

    U+061C ARABIC LETTER MARK
    U+200E LEFT-TO-RIGHT MARK
    U+200F RIGHT-TO-LEFT MARK

and probably also U+202A, U+202B, U+202C, U+202D, U+202E.

**Comment by marijnh** [comment]
We're not currently supporting bidi marks in text (in order to keep the bidi algorithm reasonably simple), and I think they are rendered as 'invalid chars' (red dots) in the editor.

**Comment by marijnh** [comment]
Oh, this wasn't in the context of CodeMirror. Err, yes, they probably should!

**Comment by marijnh** [comment]
At least the Arabic letter mark. I'm not sure about the others. They don't really associate with the character in front of them, so probably not.

**Comment by adrianheine** [comment]
Mh, maybe I don't fully understand what an »extending char« is. I thought it would be (description, not definition:) a code point that doesn't form a separate item in an editor (i. e. doesn't have a cursor position before and after). And yeah, this is about CodeMirror although we are not using this repo in CodeMirror yet. FWIW, the `ALM` is not rendered as invalid char in CodeMirror.

**Comment by marijnh** [comment]
The way I'm using extending characters is that I'm grouping them together with the first non-extending char in front of them for the purpose of cursor motion. A direction marker is conceptually a stand-alone thing, not something that modifies the shape of the thing in front of it, so I think having a cursor position before and after it makes sense.

I think I initially misunderstood how ALM works. We should probably treat it the same as the other marks, and render it as invalid.

**Comment by adrianheine** [comment]
Okay, that makes sense. So the issue I ran into probably is that ALM is not rendered as invalid in CodeMirror, which would make it a non-zero-width.
